version: "3.8"

services:
  jekyll:
    build: .
    platform: linux/arm64  # Matches your M1/M2 Mac natively
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - bundle:/srv/jekyll/vendor/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  bundle:
